const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
  approaches: { type: String },
  avatar: { type: String },
  belongTo: { type: String },
  byPass: { type: Boolean, default: false },
  color: { type: String },
  content: { type: String },
  context: { type: String },
  conversation_history: { type: Array, default: [] },
  Conversation_id: { type: String },
  conversational_AI: { type: Boolean, default: false },
  country: { type: String },
  course: { type: String },
  created_at: { type: Date, default: Date.now },
  current_Position: { type: String },
  cus_id: { type: String },
  custom_welcome_message: { type: String },
  deadlineDate: { type: Date },
  display_message: { type: String },
  dob: { type: Date },
  DOB: { type: Date },
  emailbyUser: { type: String, required: true},
  Expire_Date_and_Time: { type: Date },
  expire_time: { type: Date },
  expired_at: { type: Date },
  tenantName:{type:String,required:true},
  expiredPassword: { type: Boolean, default: false },
  f_name: { type: String },
  first_name: { type: String },
  Firstlogin: { type: Boolean, default: false },
  firstTime: { type: Boolean, default: false },
  forgot_password: { type: Boolean, default: false },
  forgotPassword: { type: Boolean, default: false },
  // gender: { type: String, enum: ['Male', 'Female', 'Other'] },
  gpt3: { type: String },
  gptPrompt: { type: String },
  grade: { type: String },
  grade_subject: { type: String },
  id: { type: mongoose.Schema.Types.ObjectId, auto: true },
  industryName: { type: String },
  InfiniteTestSeriesId: { type: String },
  instance_id: { type: String },
  instance_pvt_ip: { type: String },
  is_copy_off: { type: Boolean, default: false },
  is_download_off: { type: Boolean, default: false },
  isOTPVerified: { type: Boolean, default: false },
  isTrial: { type: Boolean, default: false },
  l_name: { type: String },
  language: { type: String },

  last_name: { type: String },
  lastlogin: { type: Date,default: [] },
  LastMathematicsModuleStatus: { type: String },
  link: { type: String },
  list_of_grade: { type: [String], default: [] },
  list_of_grade_subject: { type: [String], default: [] },
  list_of_subject: { type: [String], default: [] },
  LoginCheck: { type: Boolean, default: false },
  math_question: { type: String },
  Mathematics_Module_Response: { type: String },
  MathematicsModule: { type: String },
  metadata: { type: Object, default: {} },
  minutes: { type: Number },
  name: { type: String },
  OTP: { type: String },
  output_string: { type: String },
  output_string_step: { type: String },
  package_expire_at: { type: Date },
  Parent_email: { type: String },
  Parent_email_Status: { type: String },
  parental_consent: { type: Boolean, default: false },
  ParentalConsent: { type: Boolean, default: false },
  password: { type: String, required: true },
  Password: { type: String },
  phone: { type: String },
  Phone: { type: String },
  PIE_on_off: { type: Boolean, default: false },
  Plan: { type: String },
  policy: { type: String },
  policyage: { type: Number },
  Presentation: { type: String },
  Presentation_Current_index: { type: Number },
  Presentation_first_index: { type: Number },
  Presentation_id: { type: String },
  Presentation_last_index: { type: Number },
  Presentation_url: { type: String },
  previous_question: { type: String },
  profilePicture: { type: String },
  prompt: { type: String },
  name: { type: String },
  prompt_status: { type: String },
  prompt_status_Verification: { type: String },
  purchase: { type: String },
  question: { type: String },
  school: { type: String },
  score: { type: Number },
  email:{type: String, required: true, unique: true },
  Secondary_Parent_Emails: { type: [String], default: [] },
  Section: { type: String },
  send_email: { type: Boolean, default: false },
  session_id: { type: String },
  session_status: { type: String },
  sessionID: { type: String },
  setDeadline: { type: Date },
  signUp: { type: Date, default: Date.now },
  slot_1: { type: String },
  slot_1_time: { type: Date },
  slot_2: { type: String },
  slot_2_time: { type: Date },
  slot_3: { type: String },
  slot_3_time: { type: Date },
  solution: { type: String },
  speechSpeed: { type: Number },
  StartInfiniteTestSeries: { type: Boolean, default: false },
  StartTestSeries: { type: Boolean, default: false },
  state: { type: String },
  status: { type: String, enum: ['Active', 'Inactive'], default: 'Active' },
  steps: { type: Number },
  Streak_Count: { type: Number },
  Subscription: { type: String },
  tenantEmail: { type: String },
  tenantId: { type: mongoose.Schema.Types.ObjectId, ref: 'Tenant' },
  tenantName: { type: String },
  testprep: { type: String },
  TestSeriesId: { type: String },
  Time_out: { type: Number },
  Time_zone: { type: String, default: 'UTC' },
  Timeout_id: { type: String },
  timeZone: { type: String },
  token: { type: String },
  trial_period: { type: Number },
  whichStep: { type: Number },
  zip: { type: String },
  
});

module.exports = mongoose.model('User', userSchema);
